Create entities
db-training-etl/reference-data-microservice pull request #15
Opened 2022-10-14 11:45 UTC by loui-gft

2022-10-14 11:47 UTC, gnugomez requested changes
rename entity package to lowercase

2022-10-17 09:00 UTC, gnugomez approved these changes

2022-10-17 09:07 UTC, anntGFT approved these changes

2022-10-17 09:12 UTC, sakhmed99 approved these changes

2022-10-17 09:13 UTC, anntGFT approved these changes

2022-10-17 09:16 UTC, loui-gft commented
Modified entity package name to lower case. Added configuration script to Github workflow to make MySQL work in the test environment.

2022-10-17 09:16 UTC, merged